version: '3'
services:
  app:
    build: './docker/build/php'
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./settings/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - mysql_lib:/var/lib/mysql

volumes:
  mysql_lib: